
import { Language, Translations, Translation } from './types';

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া' },
  { code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्' },
  { code: 'brx', name: 'Bodo', nativeName: 'बरो' },
  { code: 'doi', name: 'Dogri', nativeName: 'डोगरी' },
  { code: 'kok', name: 'Konkani', nativeName: 'कोंकणी' },
  { code: 'mai', name: 'Maithili', nativeName: 'मैथिली' },
  { code: 'mni', name: 'Manipuri', nativeName: 'মণিপুরী' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली' },
  { code: 'sat', name: 'Santali', nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ' },
  { code: 'sd', name: 'Sindhi', nativeName: 'सिंधी' },
  { code: 'ks', name: 'Kashmiri', nativeName: 'کٲشُر' },
];

const en: Translation = {
  welcome: "Hello! I am Vyapara Mithra.",
  tell_me_about: "Tell me about your business.",
  placeholder_desc: "Example: I have a saree shop in Karol Bagh...",
  btn_continue: "OK / Continue",
  contact_details: "Contact Details",
  lbl_name: "Shop/Business Name",
  lbl_phone: "Phone Number",
  lbl_email: "Email Address",
  lbl_address: "Shop Address",
  btn_detect_location: "Detect Precise Live Location",
  btn_create: "Create My Website",
  btn_update: "Update Website",
  generating: "Building your website...",
  ready_msg: "Your website is ready! 🎉",
  edit_placeholder: "Tell me what to change...",
  share_whatsapp: "Share on WhatsApp",
  copy_link: "Copy Link",
  preview_title: "Preview",
  listening: "Listening...",
  tap_to_speak: "Tap to Speak",
  tap_to_edit: "Tap any text to edit directly",
  invalid_phone: "Enter a valid 10-digit number",
  history_title: "Edit History",
  no_edits: "No edits yet.",
  btn_restore: "Restore",
  btn_delete: "Delete",
  confirm_delete: "Are you sure you want to delete this history item?",
  initial_website: "Initial Website",
  restored_text: "Restored",
  manual_edit: "Manual Text Edit",
  detecting: "Detecting Precise Location...",
  location_error: "Could not detect location. Please type manually.",
  geo_not_supported: "Geolocation is not supported by your browser.",
  voice_not_supported: "Voice input is not supported in this browser.",
  mithra_break: "Mithra is taking a break",
  retry_msg: "Please click Create again to retry.",
  creating_shop_msg: "Vyapara Mithra is carefully creating your shop...",
  share_text: "Check out my new online shop!",
  placeholder_name: "Example: Ramesh Saree Center",
  placeholder_address: "Example: Street Number 10, City, Pin Code",
  placeholder_email: "Example: shop@email.com",
  login_title: "Secure Login",
  btn_send_otp: "Send OTP",
  otp_title: "Enter OTP",
  otp_desc: "We sent a 4-digit code to",
  btn_verify_login: "Verify & Enter",
  invalid_otp: "Invalid OTP. Please try again.",
  compulsory: "Compulsory",
  lbl_copyright: "© 2026 Vyapara Mithra. All rights reserved.",
  lbl_update_website: "Update Your Website",
  lbl_edit_instruction: "Tell Mithra what to add or change about your business story!",
  location_locked: "Shop Location Locked!",
  location_detect: "Detect Shop Pin Exactly",
  location_detecting_msg: "Detecting Precise Pin...",
  lbl_accuracy: "Accuracy",
  lbl_status: "Status",
  lbl_connecting: "Connecting to GPS...",
  step_analyzing: "I'm reading your business story...",
  step_designing: "Sketching a premium layout for you...",
  step_coloring: "Mixing colors that match your vibe...",
  step_finalizing: "Polishing every detail for your shop...",
  btn_confirm: "Confirm & Finalize"
};

const gu: Translation = {
  ...en,
  welcome: "નમસ્તે! હું વ્યાપાર મિત્ર છું.",
  tell_me_about: "તમારા વ્યવસાય વિશે મને કહો.",
  placeholder_desc: "ઉદાહરણ: મારે કરૂલ બાગમાં સાડીની દુકાન છે...",
  btn_continue: "ઠીક છે / આગળ વધો",
  contact_details: "સંપર્ક વિગતો",
  lbl_name: "દુકાન/વ્યવસાયનું નામ",
  lbl_phone: "ફોન નંબર",
  lbl_email: "ઈમેલ એડ્રેસ",
  lbl_address: "દુકાનનું સરનામું",
  btn_detect_location: "ચોક્કસ સ્થાન શોધો",
  btn_create: "મારી વેબસાઇટ બનાવો",
  btn_update: "વેબસાઇટ અપડેટ કરો",
  generating: "તમારી વેબસાઇટ બની રહી છે...",
  ready_msg: "તમારી વેબસાઇટ તૈયાર છે! 🎉",
  edit_placeholder: "શું બદલવું છે તે કહો...",
  preview_title: "પૂર્વાવલોકન",
  listening: "સાંભળી રહ્યો છું...",
  tap_to_speak: "બોલવા માટે ટેપ કરો",
  tap_to_edit: "ફેરફાર કરવા માટે ટેક્સ્ટ પર ટેપ કરો",
  detecting: "ચોક્કસ સ્થાન શોધી રહ્યા છીએ...",
  location_error: "સ્થાન શોધી શકાયું નથી. કૃપા કરીને જાતે ટાઈપ કરો.",
  creating_shop_msg: "વ્યાપાર મિત્ર તમારી દુકાન બનાવી રહ્યો છે...",
  login_title: "સુરક્ષિત લોગિન",
  btn_send_otp: "OTP મોકલો",
  btn_verify_login: "ચકાસો અને આગળ વધો",
  compulsory: "ဖરજિયાત",
  lbl_copyright: "© 2026 વ્યાપાર મિત્ર. સર્વાધિકાર સુરક્ષિત.",
  lbl_update_website: "તમારી વેબસાઇટ અપડેટ કરો",
  lbl_edit_instruction: "તમારા વ્યવસાયની વાર્તામાં શું ઉમેરવું કે બદલવું છે તે મિત્રને કહો!",
  location_locked: "દુકાનનું લોકેશન લોક થયું!",
  location_detect: "દુકાનનો પિન બરાબર શોધો",
  location_detecting_msg: "ચોક્કસ પિન શોધી રહ્યા છીએ...",
  step_analyzing: "હું તમારા વ્યવસાયની વાર્તા વાંચી રહ્યો છું...",
  step_designing: "તમારા માટે પ્રીમિયમ લેઆઉટ સ્કેચ કરી રહ્યો છું...",
  step_coloring: "તમારા વ્યવસાયને અનુરૂપ રંગો પસંદ કરી રહ્યો છું...",
  step_finalizing: "દરેક વિગતોને અંતિમ ઓપ આપી રહ્યો છું...",
  btn_confirm: "પુષ્ટિ કરો અને સમાપ્ત કરો"
};

const ur: Translation = {
  ...en,
  welcome: "ہیلو! میں ہوں ویاپارا مترا۔",
  tell_me_about: "مجھے اپنے کاروبار کے بارے میں بتائیں۔",
  placeholder_desc: "مثال: میری قرول باغ میں ساڑی کی دکان ہے...",
  btn_continue: "ٹھیک ہے / جاری رکھیں",
  contact_details: "رابطہ کی تفصیلات",
  lbl_name: "دکان/کاروبار کا نام",
  lbl_phone: "فون نمبر",
  lbl_email: "ای میل ایڈریس",
  lbl_address: "دکان کا پتہ",
  btn_detect_location: "درست مقام معلوم کریں",
  btn_create: "میری ویب سائٹ بنائیں",
  btn_update: "ویب سائٹ اپ ڈیٹ کریں",
  generating: "آپ کی ویب سائٹ بن رہی ہے...",
  ready_msg: "آپ کی ویب سائٹ تیار ہے! 🎉",
  edit_placeholder: "بتائیں کیا تبدیل کرنا ہے...",
  preview_title: "پیش نظارہ",
  listening: "سن رہا ہوں...",
  tap_to_speak: "بولنے کے لیے ٹیپ کریں",
  tap_to_edit: "ایڈٹ کرنے کے لیے متن پر ٹیپ کریں",
  detecting: "درست مقام تلاش کیا جا رہا ہے...",
  location_error: "مقام معلوم نہیں ہو سکا۔ براہ کرم دستی طور پر ٹائپ کریں۔",
  creating_shop_msg: "ویاپارا مترا آپ کی دکان بنا رہا ہے...",
  login_title: "محفوظ لاگ ان",
  btn_send_otp: "او ٹی پی بھیجیں",
  btn_verify_login: "تصدیق کریں",
  compulsory: "لازمی",
  lbl_copyright: "© 2026 Vyapara Mithra۔ جملہ حقوق محفوظ ہیں۔",
  lbl_update_website: "اپنی ویب سائٹ کو اپ ڈیٹ کریں",
  lbl_edit_instruction: "اپنے کاروبار کی کہانی میں کیا شامل کرنا یا تبدیل کرنا ہے، مترا کو بتائیں!",
  location_locked: "دکان کی لوکیشن لاک ہو گئی!",
  location_detect: "دکان کا پن بالکل صحیح معلوم کریں",
  location_detecting_msg: "درست پن تلاش کیا جا رہا ہے...",
  step_analyzing: "میں آپ کے کاروبار کی کہانی پڑھ رہا ہوں...",
  step_designing: "آپ کے لیے بہترین لے آؤٹ تیار کر رہا ہوں...",
  step_coloring: "آپ کے کاروبار کے لیے بہترین رنگ منتخب کر رہا ہوں...",
  step_finalizing: "آپ کی دکان کی تفصیلات کو مکمل کر رہا ہوں...",
  btn_confirm: "تصدیق اور مکمل کریں"
};

const kn: Translation = {
  ...en,
  welcome: "ನಮಸ್ಕಾರ! ನಾನು ವ್ಯಾಪಾರ ಮಿತ್ರ.",
  tell_me_about: "ನಿಮ್ಮ ವ್ಯವಹಾರದ ಬಗ್ಗೆ ನನಗೆ ತಿಳಿಸಿ.",
  placeholder_desc: "ಉದಾಹರಣೆ: ನನ್ನ ಬಳಿ ಕರೋಲ್ ಬಾಗ್‌ನಲ್ಲಿ ಸೀರೆ ಅಂಗಡಿ ಇದೆ...",
  btn_continue: "ಸರಿ / ಮುಂದುವರಿಸಿ",
  contact_details: "ಸಂಪರ್ಕ ವಿವರಗಳು",
  lbl_name: "ಅಂಗಡಿ/ವ್ಯವಹಾರದ ಹೆಸರು",
  lbl_phone: "ಫೋನ್ ಸಂಖ್ಯೆ",
  lbl_email: "ಇಮೇಲ್ ವಿಳಾಸ",
  lbl_address: "ಅಂಗಡಿಯ ವಿಳಾಸ",
  btn_detect_location: "ನಿಖರವಾದ ಲೊಕೇಶನ್ ಪತ್ತೆಹಚ್ಚಿ",
  btn_create: "ನನ್ನ ವೆಬ್‌ಸೈಟ್ ರಚಿಸಿ",
  btn_update: "ವೆಬ್‌ಸೈಟ್ ನವೀಕರಿಸಿ",
  generating: "ನಿಮ್ಮ ವೆಬ್‌ಸೈಟ್ ಸಿದ್ಧವಾಗುತ್ತಿದೆ...",
  ready_msg: "ನಿಮ್ಮ ವೆಬ್‌ಸೈಟ್ ಸಿದ್ಧವಾಗಿದೆ! 🎉",
  edit_placeholder: "ಏನನ್ನು ಬದಲಾಯಿಸಬೇಕೆಂದು ತಿಳಿಸಿ...",
  preview_title: "ಮುನ್ನೋಟ",
  listening: "ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದ್ದೇನೆ...",
  tap_to_speak: "ಮಾತನಾಡಲು ಸ್ಪರ್ಶಿಸಿ",
  tap_to_edit: "ಬದಲಾಯಿಸಲು ಯಾವುದೇ ಪಠ್ಯದ ಮೇಲೆ ಟ್ಯಾಪ್ ಮಾಡಿ",
  detecting: "ನಿಖರವಾದ ಲೊಕೇಶನ್ ಪತ್ತೆ ಮಾಡಲಾಗುತ್ತಿದೆ...",
  location_error: "ಲೊಕೇಶನ್ ಪತ್ತೆಹಚ್ಚಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಹಸ್ತಚಾಲಿತವಾಗಿ ಟೈಪ್ ಮಾಡಿ.",
  creating_shop_msg: "ವ್ಯಾಪಾರ ಮಿತ್ರ ನಿಮ್ಮ ಅಂಗಡಿಯನ್ನು ರಚಿಸುತ್ತಿದ್ದಾರೆ...",
  login_title: "ಸುರಕ್ಷಿತ ಲಾಗಿನ್",
  btn_send_otp: "OTP ಕಳುಹಿಸಿ",
  btn_verify_login: "ದೃಢೀಕರಿಸಿ",
  compulsory: "ಕಡ್ಡಾಯ",
  lbl_copyright: "© 2026 ವ್ಯಾಪಾರ ಮಿತ್ರ. ಸರ್ವ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",
  lbl_update_website: "ನಿಮ್ಮ ವೆಬ್‌ಸೈಟ್ ನವೀಕರಿಸಿ",
  lbl_edit_instruction: "ನಿಮ್ಮ ವ್ಯವಹಾರದ ಕಥೆಯಲ್ಲಿ ಏನನ್ನು ಸೇರಿಸಬೇಕು ಅಥವಾ ಬದಲಾಯಿಸಬೇಕೆಂದು ಮಿತ್ರನಿಗೆ ತಿಳಿಸಿ!",
  location_locked: "ಅಂಗಡಿಯ ಸ್ಥಳ ಲಾಕ್ ಮಾಡಲಾಗಿದೆ!",
  location_detect: "ಅಂಗಡಿಯ ಪಿನ್ ನಿಖರವಾಗಿ ಪತ್ತೆ ಮಾಡಿ",
  location_detecting_msg: "ನಿಖರವಾದ ಪಿನ್ ಪತ್ತೆ ಮಾಡಲಾಗುತ್ತಿದೆ...",
  step_analyzing: "ನಾನು ನಿಮ್ಮ ವ್ಯವಹಾರದ ಕಥೆಯನ್ನು ಓದುತ್ತಿದ್ದೇನೆ...",
  step_designing: "ನಿಮಗಾಗಿ ಪ್ರೀಮಿಯಂ ಲೇಔಟ್ ಸಿದ್ಧಪಡಿಸುತ್ತಿದ್ದೇನೆ...",
  step_coloring: "ನಿಮ್ಮ ಅಭಿರುಚಿಗೆ ತಕ್ಕ ಬಣ್ಣಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡುತ್ತಿದ್ದೇನೆ...",
  step_finalizing: "ಅಂಗಡಿಯ ಪ್ರತಿಯೊಂದು ವಿವರವನ್ನು ಅಂತಿಮಗೊಳಿಸುತ್ತಿದ್ದೇನೆ...",
  btn_confirm: "ದೃಢೀಕರಿಸಿ ಮತ್ತು ಮುಕ್ತಾಯಗೊಳಿಸಿ"
};

const ml: Translation = {
  ...en,
  welcome: "നമസ്കാരം! ഞാൻ വ്യാപാര മിത്രയാണ്.",
  tell_me_about: "നിങ്ങളുടെ ബിസിനസ്സിനെക്കുറിച്ച് എന്നോട് പറയുക.",
  placeholder_desc: "ഉദാഹരണം: കരോൾ ബാഗിൽ എനിക്കൊരു സാരി ഷോപ്പുണ്ട്...",
  btn_continue: "ശരി / തുടരുക",
  contact_details: "ബന്ധപ്പെടാനുള്ള വിവരങ്ങൾ",
  lbl_name: "ഷോപ്പ്/ബിസിനസ്സിന്റെ പേര്",
  lbl_phone: "ഫോൺ നമ്പർ",
  lbl_email: "ഇമെയിൽ വിലാസം",
  lbl_address: "ഷോപ്പ് വിലാസം",
  btn_detect_location: "കൃത്യമായ ലൊക്കേഷൻ കണ്ടെത്തുക",
  btn_create: "എന്റെ വെബ്സൈറ്റ് നിർമ്മിക്കുക",
  btn_update: "വെബ്സൈറ്റ് പുതുക്കുക",
  generating: "നിങ്ങളുടെ വെബ്സൈറ്റ് തയ്യാറാകുന്നു...",
  ready_msg: "നിങ്ങളുടെ വെബ്സൈറ്റ് തയ്യാറാണ്! 🎉",
  edit_placeholder: "എന്താണ് മാറ്റേണ്ടതെന്ന് പറയുക...",
  preview_title: "പ്രിവ്യൂ",
  listening: "ശ്രദ്ധിക്കുന്നു...",
  tap_to_speak: "സംസാരിക്കാൻ ടാപ്പ് ചെയ്യുക",
  tap_to_edit: "മാറ്റങ്ങൾ വരുത്താൻ ടെക്സ്റ്റിൽ ടാപ്പ് ചെയ്യുക",
  detecting: "കൃത്യമായ ലൊക്കേഷൻ കണ്ടെത്തുന്നു...",
  location_error: "ലൊക്കേഷൻ കണ്ടെത്താൻ കഴിഞ്ഞില്ല. ദയവായി ടൈപ്പ് ചെയ്യുക.",
  creating_shop_msg: "വ്യാപാര മിത്ര നിങ്ങളുടെ ഷോപ്പ് നിർമ്മിക്കുകയാണ്...",
  login_title: "സുരക്ഷിത ലോഗിൻ",
  btn_send_otp: "OTP അയക്കുക",
  btn_verify_login: "സ്ഥിരീകരിക്കുക",
  compulsory: "നിർബന്ധം",
  lbl_copyright: "© 2026 വ്യാപാര മിത്ര. എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം.",
  lbl_update_website: "നിങ്ങളുടെ വെബ്സൈറ്റ് പുതുക്കുക",
  lbl_edit_instruction: "നിങ്ങളുടെ ബിസിനസ്സ് കഥയിൽ എന്താണ് ചേർക്കേണ്ടതെന്നും മാറ്റേണ്ടതെന്നും മിത്രയോട് പറയുക!",
  location_locked: "കടയുടെ ലൊക്കേഷൻ ലോക്ക് ചെയ്തു!",
  location_detect: "കടയുടെ പിൻ കൃത്യമായി കണ്ടെത്തുക",
  location_detecting_msg: "കൃത്യമായ പിൻ കണ്ടെത്തുന്നു...",
  step_analyzing: "ഞാൻ നിങ്ങളുടെ ബിസിനസ്സ് കഥ വായിക്കുകയാണ്...",
  step_designing: "നിങ്ങൾക്കായി ഒരു പ്രീമിയം ലേഔട്ട് തയ്യാറാക്കുന്നു...",
  step_coloring: "നിങ്ങളുടെ ബിസിനസ്സിന് അനുയോജ്യമായ നിറങ്ങൾ തിരഞ്ഞെടുക്കുന്നു...",
  step_finalizing: "ഷോപ്പിന്റെ ഓരോ വിശദാംശങ്ങളും മിനുക്കുന്നു...",
  btn_confirm: "സ്ഥിരീകരിച്ച് പൂർത്തിയാക്കുക"
};

const pa: Translation = {
  ...en,
  welcome: "ਨਮਸਤੇ! ਮੈਂ ਵਿਆਪਾਰ ਮਿੱਤਰ ਹਾਂ।",
  tell_me_about: "ਮੈਨੂੰ ਆਪਣੇ ਕਾਰੋਬਾਰ ਬਾਰੇ ਦੱਸੋ।",
  placeholder_desc: "ਉਦਾਹਰਨ: ਮੇਰੀ ਕਰੋਲ ਬਾਗ ਵਿੱਚ ਸਾੜੀ ਦੀ ਦੁਕਾਨ ਹੈ...",
  btn_continue: "ਠੀਕ ਹੈ / ਜਾਰੀ ਰੱਖੋ",
  contact_details: "ਸੰਪਰਕ ਵੇਰਵੇ",
  lbl_name: "ਦੁਕਾਨ/ਕਾਰੋਬਾਰ ਦਾ ਨਾਮ",
  lbl_phone: "ਫੋਨ ਨੰਬਰ",
  lbl_email: "ਈਮੇਲ ਐਡਰੈੱਸ",
  lbl_address: "ਦੁਕਾਨ ਦਾ ਪਤਾ",
  btn_detect_location: "ਸਹੀ ਲੋਕੇਸ਼ਨ ਦਾ ਪਤਾ ਲਗਾਓ",
  btn_create: "ਮੇਰੀ ਵੈੱਬਸਾਈਟ ਬਣਾਓ",
  btn_update: "ਵੈੱਬਸਾਈਟ ਅਪਡੇਟ ਕਰੋ",
  generating: "ਤੁਹਾਡੀ ਵੈੱਬਸਾਈਟ ਬਣ ਰਹੀ ਹੈ...",
  ready_msg: "ਤੁਹਾਡੀ ਵੈੱਬਸਾਈਟ ਤਿਆਰ ਹੈ! 🎉",
  edit_placeholder: "ਦੱਸੋ ਕੀ ਬਦਲਣਾ ਹੈ...",
  preview_title: "ਝਲਕ",
  listening: "ਸੁਣ ਰਿਹਾ ਹਾਂ...",
  tap_to_speak: "ਬੋਲਣ ਲਈ ਦਬਾਓ",
  tap_to_edit: "ਬਦਲਣ ਲਈ ਟੈਕਸਟ 'ਤੇ ਟੈਪ ਕਰੋ",
  detecting: "ਸਹੀ ਲੋਕੇਸ਼ਨ ਲੱਭੀ ਜਾ ਰਹੀ ਹੈ...",
  location_error: "ਲੋਕੇਸ਼ਨ ਨਹੀਂ ਮਿਲੀ। ਕਿਰਪਾ ਕਰਕੇ ਖੁਦ ਟਾਈਪ ਕਰੋ।",
  creating_shop_msg: "ਵਿਆਪਾਰ ਮਿੱਤਰ ਤੁਹਾਡੀ ਦੁਕਾਨ ਬਣਾ ਰਿਹਾ ਹੈ...",
  login_title: "ਸੁਰੱਖਿਅਤ ਲੌਗਇਨ",
  btn_send_otp: "OTP ਭੇਜੋ",
  btn_verify_login: "ਤਸਦੀਕ ਕਰੋ",
  compulsory: "ਲਾਜ਼ਮੀ",
  lbl_copyright: "© 2026 ਵਿਆਪਾਰ ਮਿੱਤਰ। ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ।",
  lbl_update_website: "ਆਪਣੀ ਵੈੱਬਸਾਈਟ ਅਪਡੇਟ ਕਰੋ",
  lbl_edit_instruction: "ਮਿੱਤਰ ਨੂੰ ਦੱਸੋ ਕਿ ਤੁਹਾਡੇ ਕਾਰੋਬਾਰ ਦੀ ਕਹਾਣੀ ਵਿੱਚ ਕੀ ਜੋੜਨਾ ਜਾਂ ਬਦਲਣਾ ਹੈ!",
  location_locked: "ਦੁਕਾਨ ਦੀ ਲੋਕੇਸ਼ਨ ਲਾਕ ਹੋ ਗਈ!",
  location_detect: "ਦੁਕਾਨ ਦਾ ਪਿਨ ਬਿਲਕੁલ ਸਹੀ ਲੱਭੋ",
  location_detecting_msg: "ਸਹੀ ਪਿਨ ਲੱਭਿਆ ਜਾ ਰਿਹਾ ਹੈ...",
  step_analyzing: "ਮੈਂ ਤੁਹਾਡੇ ਕਾਰੋਬਾਰ ਦੀ ਕਹਾਣੀ ਪੜ੍ਹ ਰਿਹਾ ਹਾਂ...",
  step_designing: "ਤੁਹਾਡੇ ਲਈ ਇੱਕ ਵਧੀਆ ਲੇਆਉਟ ਤਿਆਰ ਕਰ ਰਿਹਾ ਹਾਂ...",
  step_coloring: "ਕਾਰੋਬਾਰ ਦੇ ਮੁਤਾਬਕ ਰੰਗ ਚੁਣ ਰਿਹਾ ਹਾਂ...",
  step_finalizing: "ਦੁਕਾਨ ਦੇ ਹਰ ਵੇਰਵੇ ਨੂੰ ਮੁਕੰਮਲ ਕਰ ਰਿਹਾ ਹਾਂ...",
  btn_confirm: "ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਖਤਮ ਕਰੋ"
};

const hi: Translation = {
  ...en,
  welcome: "नमस्ते! मैं व्यापार मित्र हूँ।",
  tell_me_about: "अपने व्यवसाय के बारे में बताएं।",
  placeholder_desc: "उदाहरण: मेरी करोल बाग में साड़ी की दुकान है...",
  btn_continue: "ठीक है / आगे बढ़ें",
  contact_details: "संपर्क विवरण",
  lbl_name: "दुकान/व्यवसाय का नाम",
  lbl_phone: "फ़ोन नंबर",
  lbl_email: "ईमेल एड्रेस",
  lbl_address: "दुकान का पता",
  btn_detect_location: "सटीक लोकेशन पता करें",
  btn_create: "मेरी वेबसाइट बनाएं",
  btn_update: "वेबसाइट अपडेट करें",
  generating: "वेबसाइट तैयार हो रही है...",
  ready_msg: "आपकी वेबसाइट तैयार है! 🎉",
  edit_placeholder: "बताएं क्या बदलना है...",
  preview_title: "झलक",
  listening: "सुन रहा हूँ...",
  tap_to_speak: "बोलने के लिए दबाएं",
  tap_to_edit: "बदलने के लिए किसी भी टेक्स्ट पर टैપ करें",
  detecting: "सटीक लोकेशन खोजी जा रही है...",
  location_error: "लोकेशन नहीं मिली। कृपया खुद टाइप करें।",
  creating_shop_msg: "व्यापार मित्र आपकी दुकान बना रहा है...",
  placeholder_name: "उदाहरण: रमेश साड़ी सेंटर",
  placeholder_address: "उदाहरण: गली नंबर 10, शहर, पिन कोड",
  placeholder_email: "उदाहरण: shop@email.com",
  login_title: "सुरक्षित लॉगिन",
  btn_send_otp: "OTP भेजें",
  btn_verify_login: "सत्यापित करें",
  compulsory: "अनिवार्य",
  lbl_copyright: "© 2026 व्यापार मित्र। सर्वाधिकार सुरक्षित।",
  lbl_update_website: "अपनी वेबसाइट अपडेट करें",
  lbl_edit_instruction: "मिरथा को बताएं कि आपके व्यवसाय की कहानी में क्या जोड़ना या बदलना है!",
  location_locked: "दुकान की लोकेशन लॉक हो गई!",
  location_detect: "दुकान का पिन बिल्कुल सही से पता करें",
  location_detecting_msg: "सटीक पिन खोजा जा रहा है...",
  lbl_accuracy: "सटीकता",
  lbl_status: "स्थिति",
  lbl_connecting: "जीपीएस से जुड़ रहा है...",
  step_analyzing: "मैं आपकी व्यावसायिक कहानी पढ़ रहा हूँ...",
  step_designing: "आपके लिए एक प्रीमियम लेआउट तैयार कर रहा हूँ...",
  step_coloring: "आपकी पसंद के रंगों को मिला रहा हूँ...",
  step_finalizing: "आपकी दुकान के लिए हर विवरण को पॉलिश कर रहा हूँ...",
  btn_confirm: "पुष्टि करें और समाप्त करें"
};

const bn: Translation = {
  ...en,
  welcome: "নমস্কার! আমি ব্যাপার মিত্র।",
  tell_me_about: "আপনার ব্যবসা সম্পর্কে বলুন।",
  placeholder_desc: "উদাহরণ: আমার বড়বাজারে একটি শাড়ির দোকান আছে...",
  btn_continue: "ঠিক আছে / এগিয়ে যান",
  contact_details: "যোগাযোগের বিবরণ",
  lbl_name: "দোকানের নাম",
  lbl_phone: "ফোন নম্বর",
  lbl_email: "ইমেইল অ্যাড্রেস",
  lbl_address: "ঠিকানা",
  btn_detect_location: "সঠিক লোকেশন দেখুন",
  btn_create: "আমার ওয়েবসাইট তৈরি করুন",
  btn_update: "ওয়েবসাইট আপডেট করুন",
  generating: "আপনার ওয়েবসাইট তৈরি হচ্ছে...",
  ready_msg: "আপনার ওয়েবসাইট তৈরি! 🎉",
  edit_placeholder: "কি পরিবর্তন করতে হবে বলুন...",
  preview_title: "প্রিভিউ",
  listening: "শুনছি...",
  tap_to_speak: "বলার জন্য ট্যাপ করুন",
  tap_to_edit: "এডিট করতে টেক্সটে ট্যাপ করুন",
  detecting: "সঠিক লোকেশন খোঁজা হচ্ছে...",
  location_error: "লোকেশন পাওয়া যায়নি। অনুগ্রহ করে টাইপ করুন।",
  creating_shop_msg: "ব্যাপার মিত্র আপনার দোকানটি তৈরি করছে...",
  placeholder_name: "উদাহরণ: রমেশ শাড়ী সেন্টার",
  placeholder_address: "উদাহরণ: রাস্তা নম্বর ১০, শহর, পিন কোড",
  placeholder_email: "উদাহরণ: shop@email.com",
  login_title: "সুরক্ষিত লগইন",
  btn_send_otp: "OTP পাঠান",
  btn_verify_login: "যাচাই করুন",
  compulsory: "আবশ্যিক",
  lbl_copyright: "© 2026 ব্যাপার মিত্র। সমস্ত অধিকার সংরক্ষিত।",
  lbl_update_website: "আপনার ওয়েবসাইট আপডেট করুন",
  lbl_edit_instruction: "আপনার ব্যবসার গল্পে কী যোগ করতে বা পরিবর্তন করতে হবে তা মিত্রকে বলুন!",
  location_locked: "দোকানের লোকেশন লক করা হয়েছে!",
  location_detect: "সঠিকভাবে দোকানের পিন খুঁজুন",
  location_detecting_msg: "সঠিক পিন খোঁজা হচ্ছে...",
  lbl_accuracy: "সঠিকতা",
  lbl_status: "অবস্থা",
  lbl_connecting: "জিপিএস সংযোগ করা হচ্ছে...",
  step_analyzing: "আমি আপনার ব্যবসার গল্প পড়ছি...",
  step_designing: "আপনার জন্য একটি প্রিমিয়াম লেআউট স্কেচ করছি...",
  step_coloring: "আপনার ব্যবসার রঙের সাথে সামঞ্জস্য রাখছি...",
  step_finalizing: "আপনার দোকানের জন্য প্রতিটি বিবরণ পলিশ করছি...",
  btn_confirm: "নিশ্চিত করুন এবং শেষ করুন"
};

const te: Translation = {
  ...en,
  welcome: "నమస్కారం! నేను వ్యాపార మిత్రను.",
  tell_me_about: "మీ వ్యాపారం గురించి చెప్పండి.",
  placeholder_desc: "ఉదాహరణ: నాకు అమీర్‌పేటలో చీరల దుకాణం ఉంది...",
  btn_continue: "సరే / కొనసాగించు",
  contact_details: "సంప్రదింపు వివరాలు",
  lbl_name: "దుకాణం పేరు",
  lbl_phone: "ఫోన్ నంబర్",
  lbl_email: "ఈమెయిల్ చిరునామా",
  lbl_address: "దుకాణం చిరునామా",
  btn_detect_location: "ఖచ్చితమైన లొకేషన్ గుర్తించు",
  btn_create: "నా వెబ్‌సైట్‌ను సృష్టించండి",
  btn_update: "వెబ్‌సైట్‌ను అప్‌డేట్ చేయండి",
  generating: "మీ వెబ్‌సైట్ సిద్ధమవుతోంది...",
  ready_msg: "మీ వెబ్‌సైట్ సిద్ధంగా ఉంది! 🎉",
  edit_placeholder: "ఏమి మార్చాలో చెప్పండి...",
  preview_title: "మునుజూపు",
  listening: "వింటున్నాను...",
  tap_to_speak: "మాట్లాడటానికి నొక్కండి",
  tap_to_edit: "మార్చడానికి టెక్స్ట్ పై నొక్కండి",
  detecting: "లొకేషన్ వెతుకుతున్నాము...",
  location_error: "లొకేషన్ దొరకలేదు. దయచేసి టైಪ್ చేయండి.",
  creating_shop_msg: "వ్యాపార మిత్ర మీ దుకాణాన్ని సృష్టిస్తోంది...",
  placeholder_name: "ఉదాహరణ: రమేష్ శారీ సెంటర్",
  placeholder_address: "ఉదాహరణ: వీధి నంబర్ 10, నగరం, పిన్ కోడ్",
  placeholder_email: "ఉదాహరణ: shop@email.com",
  login_title: "సురక్షిత లాగిన్",
  btn_send_otp: "OTP పంపండి",
  btn_verify_login: "ధృవీకరించండి",
  compulsory: "తప్పనిసరి",
  lbl_copyright: "© 2026 వ్యాపార మిత్ర. సర్వ హక్కులు ప్రత్యేకించబడ్డాయి.",
  lbl_update_website: "మీ వెబ్‌సైట్‌ను అప్‌డేట్ చేయండి",
  lbl_edit_instruction: "మీ వ్యాపార కథనానికి ఏమి జోడించాలో లేదా మార్చాలో మిత్రకు చెప్పండి!",
  location_locked: "దుకాణం లొకేషన్ లాక్ చేయబడింది!",
  location_detect: "దుకాణం పిన్ ఖచ్చితంగా గుర్తించండి",
  location_detecting_msg: "ఖచ్చితమైన పిన్ కోసం వెతుకుతున్నాము...",
  lbl_accuracy: "ఖచ్చితత్వం",
  lbl_status: "స్థితి",
  lbl_connecting: "GPS కనెక్ట్ అవుతోంది...",
  step_analyzing: "నేను మీ వ్యాపార కథనాన్ని చదువుతున్నాను...",
  step_designing: "మీ కోసం ప్రీమియం లేఅవుట్‌ను రూపొందిస్తున్నాను...",
  step_coloring: "మీ వ్యాపారానికి సరిపోయే రంగులను కలుపుతున్నాను...",
  step_finalizing: "మీ షాప్ కోసం ప్రతి వివరాలను మెరుగుపరుస్తున్నాను...",
  btn_confirm: "ధృవీకరించి పూర్తి చేయండి"
};

const ta: Translation = {
  ...en,
  welcome: "வணக்கம்! நான் வியாபார மித்ரா.",
  tell_me_about: "உங்கள் வணிகத்தைப் பற்றிச் சொல்லுங்கள்.",
  placeholder_desc: "உதாரணம்: என்னிடம் பாரிமுனையில் புடவைக் கடை உள்ளது...",
  btn_continue: "சரி / தொடரவும்",
  contact_details: "தொடர்பு விவரங்கள்",
  lbl_name: "கடையில் பெயர்",
  lbl_phone: "தொலைபேசி எண்",
  lbl_email: "மின்னஞ்சல் முகவரி",
  lbl_address: "கடை முகவரி",
  btn_detect_location: "துல்லியமான இடத்தைக் கண்டறி",
  btn_create: "எனது வலைத்தளத்தை உருவாக்கு",
  btn_update: "வலைத்தளத்தைப் புதுப்பி",
  generating: "வலைத்தளம் உருவாக்கப்படுகிறது...",
  ready_msg: "வலைத்தளம் தயார்! 🎉",
  edit_placeholder: "என்ன மாற்ற வேண்டும் என்று சொல்லுங்கள்...",
  preview_title: "முன்னோட்டம்",
  listening: "கேட்டுக்கொண்டிருக்கிறேன்...",
  tap_to_speak: "பேச தட்டவும்",
  tap_to_edit: "மாற்ற உரையைக் கிளிக் செய்யவும்",
  detecting: "இடத்தைக் கண்டறிகிறது...",
  location_error: "இடத்தைக் கண்டறிய முடியவில்லை. கைமுறையாகத் தட்டச்சு செய்யவும்.",
  creating_shop_msg: "வியாபார மித்ரா உங்கள் கடையை உருவாக்குகிறது...",
  placeholder_name: "உதாரணம்: ரமேஷ் புடவை மையம்",
  placeholder_address: "உதாரணம்: தெரு எண் 10, நகரம், பின் குறியீடு",
  placeholder_email: "உதாரணம்: shop@email.com",
  login_title: "பாதுகாப்பான உள்நுழைவு",
  btn_send_otp: "OTP அனுப்பு",
  btn_verify_login: "சரிபார்க்கவும்",
  compulsory: "கட்டாயம்",
  lbl_copyright: "© 2026 வியாபார மித்ரா. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
  lbl_update_website: "உங்கள் வலைத்தளத்தைப் புதுப்பிக்கவும்",
  lbl_edit_instruction: "உங்கள் வணிகக் கதையில் எதைச் சேர்க்க வேண்டும் அல்லது மாற்ற வேண்டும் என்று மித்ராவிடம் சொல்லுங்கள்!",
  location_locked: "கடை இருப்பிடம் உறுதி செய்யப்பட்டது!",
  location_detect: "கடை இருப்பிடத்தை சரியாக கண்டறியவும்",
  location_detecting_msg: "துல்லியமான இடத்தை தேடுகிறது...",
  lbl_accuracy: "துல்லியம்",
  lbl_status: "நிலை",
  lbl_connecting: "ஜிபிஎஸ் உடன் இணைக்கப்படுகிறது...",
  step_analyzing: "நான் உங்கள் வணிகக் கதையைப் படிக்கிறேன்...",
  step_designing: "உங்களுக்காக ஒரு பிரீமியம் தளத்தை வடிவமைக்கிறேன்...",
  step_coloring: "உங்கள் வணிகத்திற்கு ஏற்ற வண்ணங்களைச் சேர்க்கிறேன்...",
  step_finalizing: "உங்கள் கடைக்கான ஒவ்வொரு விவரத்தையும் மெருகேற்றுகிறேன்...",
  btn_confirm: "உறுதி செய்து முடிக்கவும்"
};

const mr: Translation = {
  ...en,
  welcome: "नमस्कार! मी व्यापार मित्र आहे.",
  tell_me_about: "तुमच्या व्यवसायाबद्दल सांगा.",
  placeholder_desc: "उदाहरण: माझे दादरमध्ये साडीचे दुकान आहे...",
  btn_continue: "ठीक आहे / पुढे जा",
  contact_details: "संपर्क तपशील",
  lbl_name: "दुकानाचे नाव",
  lbl_phone: "फोन नंबर",
  lbl_email: "ईमेल पत्ता",
  lbl_address: "दुकानाचे पत्ता",
  btn_detect_location: "अચૂક लोकेशन शोधा",
  btn_create: "માઝી वेबसाइट तयार करा",
  btn_update: "वेबसाइट अपडेट करा",
  generating: "वेबसाइट तयार होत आहे...",
  ready_msg: "वेबसाइट तयार आहे! 🎉",
  edit_placeholder: "काय बदलायचे ते सांगा...",
  preview_title: "पूर्वाવલોકન",
  listening: "ऐकत आहे...",
  tap_to_speak: "बोलण्यासाठी दाबा",
  tap_to_edit: "બદલ્યાસાઠી મજકુરાવર ટૅપ કરા",
  detecting: "લોકેશન શોધત આહે...",
  location_error: "લોકેશન સાપડલે નાહી. કૃપયા ટાઈપ કરા.",
  creating_shop_msg: "વ્યાપાર મિત્ર તુમચે દુકાન તૈયાર કરત આહે...",
  placeholder_name: "ઉદાહરણ: રમેશ સાડી સેન્ટર",
  placeholder_address: "ઉદાહરણ: ગલ્લી નંબર ૧૦, શહર, પિન કોડ",
  placeholder_email: "ઉદાહરણ: shop@email.com",
  login_title: "સુરક્ષિત લોગિન",
  btn_send_otp: "OTP પાઠવાય",
  btn_verify_login: "સત્યાપિત કરા",
  compulsory: "અનિવાર્ય",
  lbl_copyright: "© 2026 વ્યાપાર મિત્ર. સર્વ હક્ક રાખીવ.",
  lbl_update_website: "તુમચી વેબસાઈટ અપડેટ કરા",
  lbl_edit_instruction: "તુમચા વ્યવસાયાચા કથેત કાય જોડાયચે કિંવા બદલાયચે તે મિત્રાલા સાંગા!",
  location_locked: "દુકાણાચે લોકેશન લોક ઝાલે!",
  location_detect: "દુકાણાચે પિન અચૂકપણે શોધા",
  location_detecting_msg: "અચૂક પિન શોધત આહે...",
  lbl_accuracy: "અચૂકતા",
  lbl_status: "સ્થિતિ",
  lbl_connecting: "જીપીએસશી કનેક્ટ હોત આહે...",
  step_analyzing: "मी तूमची व्यवसाय कथा वाचत आहे...",
  step_designing: "तुमच्यासाठी प्रीमियम मांडणी तयार करत आहे...",
  step_coloring: "तुमच्या व्यवसायाला साಜೆसे रंग मिसळत आहे...",
  step_finalizing: "तुमच्या दुकानासाठी प्रत्येक तपशील पॉलिश करत आहे...",
  btn_confirm: "पुष्टी करा आणि समाप्त करा"
};

// Defined missing translation objects as fallbacks to fix shorthand property scope errors.
const or: Translation = { ...en };
const as: Translation = { ...en };
const sa: Translation = { ...en };
const ne: Translation = { ...en };

export const TRANSLATIONS: Translations = {
  en, hi, bn, te, mr, ta, gu, ur, kn, ml, pa, or, as, sa, ne,
  brx: { ...en, compulsory: "गोनां", lbl_copyright: "© 2026 Vyapara Mithra. गासै मोनथायफोরা रैखाथि खालामजाबाय।", lbl_update_website: "नोंथांनि वेबसाइटखौ आपडेट खालाम", location_locked: "দকাননি জায়গাया लक जाबाय!", location_detect: "দকাননি पिनखौ थि बिचार खालाम", btn_confirm: "थि खालाम आरो फोजोब" },
  doi: { ...en, compulsory: "जरूरी", lbl_copyright: "© 2026 Vyapara Mithra. सारे अधिकार सुरक्षित न।", lbl_update_website: "अपनी वेबसाइट अपडेट करो", location_locked: "दुकाने दी लोकेशन लाक होई गेई!", location_detect: "दुकाने दा पिन सही लब्भो", btn_confirm: "पुष्टि करो ते खत्म करो" }, 
  kok: { ...en, compulsory: "सक्तीचें", lbl_copyright: "© 2026 वेपार मित्र. सगळे હक्क રાखून दवरल्यात.", lbl_update_website: "तुमची वेबसाईट अपडेट करा", location_locked: "दुकाणाची सुवात लॉक जाली!", location_detect: "दुकाણાಚೋ पिन अचूक सोदून काढा", btn_confirm: "खात्री करा आणि सोंಪवा" }, 
  mai: { ...en, compulsory: "अनिवार्य", lbl_copyright: "© 2026 व्यापार मित्र। सर्वाधिकार सुरक्षित।", lbl_update_website: "अपन वेबसाइट अपडेट करू", location_locked: "दुकानक स्थान लॉक भ गेल!", location_detect: "दुकानक पिन सही सँ पता लगाउ", btn_confirm: "पुष्टि करू आर समाप्त करू" }, 
  mni: { ...en, compulsory: "মথৌ তাবা", lbl_copyright: "© 2026 ব্যাপারা মিত্র। হক পুম্নমক শেন্নরে।", lbl_update_website: "নহাক্কী ওয়েবসাইট অদু আপডেট তৌবীয়ু", location_locked: "দোকানগী লৈফম লক তৌরে!", location_detect: "দোকানগী পিন চুম্না থিবীউ", btn_confirm: "চুমথোকউ অমসুং লোইশিনবীয়ু" },
  sat: { ...en, compulsory: "ᱞᱟᱹᱠᱛᱤᱭᱟᱱ", lbl_copyright: "© 2026 Vyapara Mithra. ᱡᱚᱛᱚ ᱟᱹᱭᱫᱟᱹᱨ ᱨᱟᱠᱷᱟ ᱫᱚহᱚ ᱮᱱᱟ।", lbl_update_website: "ᱟᱢᱟᱜ ᱣᱮᱵᱽᱥᱟᱭᱤޓ ᱟᱯᱰᱮᱴ ᱢᱮ", location_locked: "দোকান রেনাঃ ঠাঁও লক এনা!", location_detect: "দোকান রেনাঃ পিন সঠীক তে সেঁদরা মে", btn_confirm: "ᱥᱟᱹᱨᱤ ᱢᱮ ᱟᱨ ᱢᱩᱪᱟᱹᱫ ᱢᱮ" }, 
  sd: { ...en, compulsory: "لازمي", lbl_copyright: "© 2026 Vyapara Mithra. سڀ حق محفوظ آهن.", lbl_update_website: "پنهنجي ويب سائيٽ کي اپ ڊيٽ ڪريو", location_locked: "دڪان جي لوڪيશન لاڪ ٿي وئي!", location_detect: "دڪان جو پن صحيح طرح معلوم ڪريو", btn_confirm: "پڪ ڪريو ۽ ختم ڪريو" }, 
  ks: { ...en, compulsory: "لازمی", lbl_copyright: "© 2026 Vyapara Mithra. تَمام حَقوق مَحفوظ چھِ۔", lbl_update_website: "پَنُن ویب سایٹ کٔریو اپڈیٹ", location_locked: "دکانچہٕ لوکیشن لاک گٔیهِ!", location_detect: "دکانُک پن بالکل صحیح معلوم کٔریو", btn_confirm: "تصدیق کٔریو تہٕ ختٕم کٔریو" }
};
